# Generated by Django 5.1.2 on 2025-02-13 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_doctornote_actionablestep'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionablestep',
            name='duration',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='actionablestep',
            name='frequency',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
    ]
